# Generated by Django 4.1.3 on 2023-02-02 08:30

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerPaymentPending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField()),
                ('payment_status', models.CharField(blank=True, max_length=20, null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('orders_pending', models.JSONField(default=dict)),
                ('postal_code', models.CharField(max_length=9)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=128)),
                ('locality', models.TextField(help_text='town, street, house, etc')),
                ('receive_newsletter', models.BooleanField(default=True, help_text='receive newsletter new product and discount')),
            ],
        ),
        migrations.CreateModel(
            name='Buyers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('payment_date', models.DateTimeField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('purchases', models.JSONField(default=dict)),
                ('postal_code', models.CharField(max_length=9)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=128)),
                ('locality', models.TextField(help_text='town, street, house, etc')),
            ],
        ),
    ]
