# Generated by Django 4.1.3 on 2023-02-11 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_payment_date_buyers_captured_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyers',
            name='captured_at',
        ),
    ]
