# Generated by Django 4.1.3 on 2023-03-14 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_buyers_captured_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyers',
            name='country',
        ),
        migrations.RemoveField(
            model_name='buyers',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='buyers',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='buyers',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='buyers',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='buyers',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='buyers',
            name='state',
        ),
        migrations.AddField(
            model_name='buyers',
            name='delivery_data',
            field=models.JSONField(default=dict, verbose_name='phone, name, address'),
        ),
        migrations.CreateModel(
            name='OrderPending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_pending', to='users.buyerpaymentpending')),
            ],
        ),
    ]
