# Generated by Django 4.1.3 on 2023-04-24 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_buyers_country_remove_buyers_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderPending',
        ),
    ]
