# Generated by Django 4.1.3 on 2023-04-24 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_delete_orderpending'),
    ]

    operations = [
        migrations.RenameModel('Buyers', 'Buyer')
    ]
    atomic = False
