version: '3.3'

services:
  web:
    container_name: online_shop_container
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: online_shop_web
    # '/start' is the shell script used to run the service
    command: /start
    # this volume is used to map the files and folders on the host to the container
    # so if we change code on the host, code in the docker container will also be changed
    volumes:
      - .:/app
    ports:
      - 8000:8000
    # env_file is used to manage the env variables of our project
    env_file:
      - ./.env
    depends_on:
      - redis
      - db

  db:
    container_name: postgres_container
    image: postgres:12.13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - PGDATA=${PGDATA}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    env_file:
      - ./.env
    volumes:
      - ./pgadmin:/var/tmp/pgadmin
    ports:
      - 5050:80
    depends_on:
      - db

  redis:
    container_name: redis_container
    image: redis:5.0.7

  celery_worker:
    container_name: celery_worker_container
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: online_shop_celery_worker
    command: /start-celeryworker
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - redis
      - db

  celery_beat:
    container_name: celery_beat_container
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: online_shop_celery_beat
    command: /start-celerybeat
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - redis
      - db

  flower:
    container_name: flower_container
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: online_shop_celery_flower
    command: /start-flower
    volumes:
      - .:/app
    env_file:
      - ./.env
    ports:
      - 5555:5555
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
  pgadmin: